# Generated by Django 3.0.8 on 2020-12-05 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slink',
            name='l_name',
            field=models.CharField(max_length=500),
        ),
    ]
