# Generated by Django 3.0.8 on 2021-04-04 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srt', '0002_auto_20201206_0302'),
    ]

    operations = [
        migrations.CreateModel(
            name='ulink',
            fields=[
                ('name', models.CharField(max_length=90)),
                ('l_id', models.AutoField(primary_key=True, serialize=False)),
                ('l_name', models.CharField(max_length=500)),
            ],
        ),
    ]
