# Generated by Django 3.0.8 on 2021-04-15 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srt', '0004_clink'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(max_length=40)),
                ('messege', models.CharField(max_length=1000)),
            ],
        ),
    ]
