# Generated by Django 3.0.8 on 2021-04-15 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srt', '0007_auto_20210415_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='timestamp',
            field=models.DateField(),
        ),
    ]
