# Generated by Django 3.0.8 on 2021-04-15 14:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srt', '0008_auto_20210415_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='timestamp',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
