# Generated by Django 3.0.8 on 2021-04-15 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srt', '0011_auto_20210415_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='timestamp',
        ),
    ]
